// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCECYl9u6OHbVwaQy--Lxl1ydm6WugBMTs',
    appId: '1:49793172042:android:f977641f536a4e11245cb3',
    messagingSenderId: '49793172042',
    projectId: 'flutter-delhi-dating',
    storageBucket: 'flutter-delhi-dating.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr62AHWzmto271OhrxZ9OK_TLHQx3waic',
    appId: '1:49793172042:ios:11b9c6e9ceb5b1a8245cb3',
    messagingSenderId: '49793172042',
    projectId: 'flutter-delhi-dating',
    storageBucket: 'flutter-delhi-dating.firebasestorage.app',
    androidClientId: '49793172042-ar9d5qna9smkma4rbvssa6rh8pr8lckb.apps.googleusercontent.com',
    iosClientId: '49793172042-p6m44qgb7q44l6lcovv8s01n5chbru6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingApp',
  );

}